{"name": "test_sample2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6", "trace": ">   ???\nE   assert 5 == 6\n\nC:\\Users\\Om\\PycharmProjects\\pythonProject\\28 may 24(Api)\\test_api04.py:8: AssertionError"}, "start": 1717004636748, "stop": 1717004636749, "uuid": "7d9cdad6-5834-4d63-8172-3a183a1e3b62", "historyId": "d8288600ace008c18eb5c81dbf3e2298", "testCaseId": "d8288600ace008c18eb5c81dbf3e2298", "fullName": "May.test_api04#test_sample2", "labels": [{"name": "parentSuite", "value": "May"}, {"name": "suite", "value": "test_api04"}, {"name": "host", "value": "DESKTOP-IKKSMLA"}, {"name": "thread", "value": "14904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "May.test_api04"}]}